#live server configurations
##########################
#   RTMP configurations  #
##########################
[rtmp]
enabled = true
port = 1935
[rtmp.webhooks]
enabled = true
publish_url = "http://localhost:8080/api/v1/publish"
publish_done_url = "http://localhost:8080/api/v1/publish_done"

##########################
# HTTPAPI configurations #
##########################
[httpapi]
enabled = true
port = 8000

##########################
#   LOG configurations   #
##########################
[log]
level = "info"
#level = "trace"
