[package]
name = "xflv"
description = "flv library."
version = "1.1.0"
authors = ["HarlanC <wawacry@qq.com"]
repository = "https://github.com/guaclive/gms"
license = "MIT"
readme = "README.md"
categories = ["flv"]
keywords = ["flv", "video", "streaming"]
edition = "2018"

[dependencies]
byteorder = "1.4.2"
bytes = "1.0.0"
failure = "0.1.1"
bitvec = "1.0.1"
bytesio = {path = "../../bytesio/"}
tracing = "^0.1"
serde = { version = "1.0", features = ["derive", "rc"] }
#h264-decoder = "0.1.0"
h264-decoder = { path = "../../codec/h264/" }
